version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: memotion-db
    ports:
      # Map host port 5333 to container port 5432
      - "5333:5333"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memotion_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - memotion-network

volumes:
  postgres_data:

networks:
  memotion-network:
    driver: bridge
