name: CI/CD FastAPI

on:
  push:
    branches:
      - main  # chỉ chạy khi có code mới trên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Build Docker image
        run: |
          echo "Building Docker image: ${{ secrets.DOCKER_IMAGE }}"
          docker build -t ${{ secrets.DOCKER_IMAGE }} .

      - name: Save Docker image to tar
        run: |
          echo "Building Docker image: ${{ secrets.DOCKER_IMAGE }}"
          docker save ${{ secrets.DOCKER_IMAGE }}:latest -o fastapi_app.tar
          
      - name: Debug SSH key format
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" | head -n 5
          echo "..."
           
      - name: Deploy to server manually
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
          DOCKER_CONTAINER: ${{ secrets.DOCKER_CONTAINER }}
          PORT : ${{ secrets.PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "$SERVER_SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p 2222 -H $SERVER_HOST >> ~/.ssh/known_hosts
          scp -P 2222 -i ~/.ssh/deploy_key fastapi_app.tar ${SERVER_USER}@${SERVER_HOST}:~/
          ssh -p 2222 -i ~/.ssh/deploy_key ${SERVER_USER}@${SERVER_HOST} << EOF
            docker load -i ~/fastapi_app.tar
            docker stop ${DOCKER_CONTAINER} || true
            docker rm ${DOCKER_CONTAINER} || true
            docker run -d --name ${DOCKER_CONTAINER} \
              --restart unless-stopped \
              --add-host host.docker.internal:host-gateway \
              -e SQL_DATABASE_URL="postgresql://postgres:postgres@host.docker.internal:5333/memotion_db" \
              -e SECRET_KEY="changeme" \
              -e PROJECT_NAME="Memotion" \
              -p ${PORT} ${DOCKER_IMAGE}
          EOF
